// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM_oF7iLQ-Ohu4VGcrVLmHYFBws3OvfGA',
    appId: '1:226351628644:web:a0aeda25144ad75fa8fa71',
    messagingSenderId: '226351628644',
    projectId: 'myfirssfirebase',
    authDomain: 'myfirssfirebase.firebaseapp.com',
    databaseURL: 'https://myfirssfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirssfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk1R_113BkGO48CptzeR8G7CoexAxcnd0',
    appId: '1:226351628644:android:45d7a1c17303c47da8fa71',
    messagingSenderId: '226351628644',
    projectId: 'myfirssfirebase',
    databaseURL: 'https://myfirssfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirssfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrAWbw6_rNaXTxBMcbgM-CoEIc1jpP63s',
    appId: '1:226351628644:ios:86581f509371f37fa8fa71',
    messagingSenderId: '226351628644',
    projectId: 'myfirssfirebase',
    databaseURL: 'https://myfirssfirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myfirssfirebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodolist',
  );
}
